module EX.P2 where

-- Problem 2

-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

p2 :: Int -> Int
p2 n = sum $ filter even [fibo x | x <- [1..n]] 

fibo :: Int -> Int
fibo 1 = 1
fibo 2 = 2
fibo n = (fibo (n-1)) + (fibo (n-2))
